// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJuRmExz82UrHvPrVqvRY2I3zxS3fjw3Y',
    appId: '1:749473145419:web:1aae37e4689b52f8a363ce',
    messagingSenderId: '749473145419',
    projectId: 'illustrator-guide',
    authDomain: 'illustrator-guide.firebaseapp.com',
    storageBucket: 'illustrator-guide.firebasestorage.app',
    measurementId: 'G-LFD2PN21D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPc0mSq_DfTjk3n1mddzr2TT8f7G5D24',
    appId: '1:749473145419:android:8566e80c489a2f62a363ce',
    messagingSenderId: '749473145419',
    projectId: 'illustrator-guide',
    storageBucket: 'illustrator-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBypxFXl9BaKX_dGuV1c2ko3i7kdvbLtd4',
    appId: '1:749473145419:ios:ac7d68c8838b3373a363ce',
    messagingSenderId: '749473145419',
    projectId: 'illustrator-guide',
    storageBucket: 'illustrator-guide.firebasestorage.app',
    iosBundleId: 'com.example.illustratorGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBypxFXl9BaKX_dGuV1c2ko3i7kdvbLtd4',
    appId: '1:749473145419:ios:ac7d68c8838b3373a363ce',
    messagingSenderId: '749473145419',
    projectId: 'illustrator-guide',
    storageBucket: 'illustrator-guide.firebasestorage.app',
    iosBundleId: 'com.example.illustratorGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJuRmExz82UrHvPrVqvRY2I3zxS3fjw3Y',
    appId: '1:749473145419:web:323a686227895762a363ce',
    messagingSenderId: '749473145419',
    projectId: 'illustrator-guide',
    authDomain: 'illustrator-guide.firebaseapp.com',
    storageBucket: 'illustrator-guide.firebasestorage.app',
    measurementId: 'G-87MXPSZ6FY',
  );

}